/**
 * 编译所有 Solidity 合约并生成 JS 数据文件
 * 
 * 输出文件：
 *   - contract_data.js      (ModaMintToken ABI + Bytecode)
 *   - tracker_data.js        (DividendTracker ABI + Bytecode)
 *   - tax_distributor_data.js (TaxDistributor ABI + Bytecode)
 *   - vanity_deployer_data.js (VanityDeployer ABI + Bytecode)
 */

const fs = require('fs');
const path = require('path');
const solc = require('solc');

const CONTRACTS_DIR = path.join(__dirname, 'contracts');
const OUTPUT_DIR = __dirname;

// ── 读取所有合约源码 ──
function readContract(name) {
    return fs.readFileSync(path.join(CONTRACTS_DIR, name), 'utf8');
}

const sources = {
    'Interfaces.sol':       { content: readContract('Interfaces.sol') },
    'DividendTracker.sol':  { content: readContract('DividendTracker.sol') },
    'TaxDistributor.sol':   { content: readContract('TaxDistributor.sol') },
    'VanityDeployer.sol':   { content: readContract('VanityDeployer.sol') },
    'ModaMintToken.sol':    { content: readContract('ModaMintToken.sol') },
};

// ── 编译 ──
console.log('Compiling contracts with solc 0.8.19...');

const input = {
    language: 'Solidity',
    sources: sources,
    settings: {
        outputSelection: {
            '*': {
                '*': ['abi', 'evm.bytecode.object', 'evm.deployedBytecode.object'],
            },
        },
        optimizer: {
            enabled: true,
            runs: 200,
        },
        viaIR: true,
    },
};

const output = JSON.parse(solc.compile(JSON.stringify(input), {
    import: function(path) {
        // Resolve relative imports
        const resolved = path.startsWith('./') ? path : './' + path;
        const fullPath = require('path').join(CONTRACTS_DIR, resolved);
        if (fs.existsSync(fullPath)) {
            return { contents: fs.readFileSync(fullPath, 'utf8') };
        }
        return { error: 'File not found: ' + path };
    }
}));

// ── 检查编译错误 ──
if (output.errors) {
    let hasError = false;
    output.errors.forEach(err => {
        const severity = err.severity;
        if (severity === 'error') {
            hasError = true;
            console.error('ERROR:', err.formattedMessage);
        } else if (severity === 'warning') {
            console.warn('WARNING:', err.formattedMessage);
        }
    });
    if (hasError) {
        console.error('\nCompilation failed!');
        process.exit(1);
    }
}

// ── 辅助函数：提取合约数据 ──
function getContractData(sourceFile, contractName) {
    const c = output.contracts[sourceFile][contractName];
    if (!c) {
        console.error(`Contract ${contractName} not found in ${sourceFile}!`);
        return null;
    }
    return {
        abi: c.abi,
        bytecode: '0x' + c.evm.bytecode.object,
        deployedBytecode: '0x' + c.evm.deployedBytecode.object,
    };
}

// ── 生成 JS 文件 ──
function writeJS(filename, varName, data) {
    const abiStr = JSON.stringify(data.abi);
    const content = `// Auto-generated by build.js — DO NOT EDIT
var ${varName} = {
  ABI: ${abiStr},
  BYTECODE: "${data.bytecode}",
  DEPLOYED_BYTECODE: "${data.deployedBytecode}"
};
`;
    const filePath = path.join(OUTPUT_DIR, filename);
    fs.writeFileSync(filePath, content);
    console.log(`  ✓ ${filename} (${(content.length / 1024).toFixed(1)} KB)`);
}

// ── 主合约：ModaMintToken ──
const mainData = getContractData('ModaMintToken.sol', 'ModaMintToken');
if (mainData) {
    writeJS('contract_data.js', 'CONTRACT_DATA', mainData);
}

// ── DividendTracker ──
const trackerData = getContractData('DividendTracker.sol', 'DividendTracker');
if (trackerData) {
    writeJS('tracker_data.js', 'TRACKER_DATA', trackerData);
}

// ── TaxDistributor ──
const taxData = getContractData('TaxDistributor.sol', 'TaxDistributor');
if (taxData) {
    writeJS('tax_distributor_data.js', 'TAX_DISTRIBUTOR_DATA', taxData);
}

// ── VanityDeployer ──
const vanityData = getContractData('VanityDeployer.sol', 'VanityDeployer');
if (vanityData) {
    // launch.html 引用的是 VANITY_DEPLOYER_ABI 和 VANITY_DEPLOYER_BYTECODE（注意是独立变量，非对象属性！）
    const abiStr = JSON.stringify(vanityData.abi);
    const content = `// Auto-generated by build.js — DO NOT EDIT
var VANITY_DEPLOYER_ABI = ${abiStr};
var VANITY_DEPLOYER_BYTECODE = "${vanityData.bytecode}";
var VANITY_DEPLOYER_DEPLOYED_BYTECODE = "${vanityData.deployedBytecode}";
`;
    const filePath = path.join(OUTPUT_DIR, 'vanity_deployer_data.js');
    fs.writeFileSync(filePath, content);
    console.log(`  ✓ vanity_deployer_data.js (${(content.length / 1024).toFixed(1)} KB)`);
}

// ── 同样生成 admin.html 需要的 DISTRIBUTOR_DATA ──
// admin.html 引用了 distributor_data.js（旧版 DividendTracker 兼容命名）
if (trackerData) {
    const abiStr = JSON.stringify(trackerData.abi);
    const content = `// Auto-generated by build.js — DO NOT EDIT (compat alias for admin.html)
var DISTRIBUTOR_DATA = {
  ABI: ${abiStr},
  BYTECODE: "${trackerData.bytecode}",
  DEPLOYED_BYTECODE: "${trackerData.deployedBytecode}"
};
`;
    const filePath = path.join(OUTPUT_DIR, 'distributor_data.js');
    fs.writeFileSync(filePath, content);
    console.log(`  ✓ distributor_data.js (compat alias)`);
}

console.log('\n✅ All contracts compiled successfully!');
console.log('Output files in:', OUTPUT_DIR);
